listener 1883
allow_anonymous true

# Konfigurasi untuk WebSocket (Opsional, sangat berguna jika Frontend React ingin subscribe langsung via browser)
listener 9001
protocol websockets
allow_anonymous true
